<?php

namespace MyShop\DefaultBundle\Repository;
use MyShop\DefaultBundle\Entity\Customer;
use MyShop\DefaultBundle\Entity\CustomerOrder;

/**
 * CustomerOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerOrderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @var CustomerOrder
    */
    public function getOrCreateOrderByCustomer(Customer $customer)
    {
        $manager = $this->getEntityManager();

        $dql = 'select o from MyShopDefaultBundle:CustomerOrder o where o.customer = :customer and o.status = :status';
        $order = $manager->createQuery($dql)->setParameters([
            'customer' => $customer,
            'status' => CustomerOrder::STATUS_OPEN
        ])->getOneOrNullResult();

        if ($order == null) {
            $order = new CustomerOrder();
            $customer->addOrder($order);
            $manager->persist($order);
            $manager->flush();
        }

        return $order;
    }
}
