<?php

namespace MyShop\DefaultBundle\Repository;

/**
 * OrderProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderProductRepository extends \Doctrine\ORM\EntityRepository
{
}
